Update desktop.yml

diff --git a/.github/workflows/desktop.yml b/.github/workflows/desktop.yml
--- a/.github/workflows/desktop.yml
+++ b/.github/workflows/desktop.yml
@@ -1,33 +1,16 @@
-name: Windows Store app
-# https://medium.com/codechai/flutter-app-couldnt-find-libflutter-so-c95ad81cbccd
+name: Deploy MSIX to GitHub
+
 on:
-  push:
-    branches: [desktop]
+  release:
+    types:
+      - published
+
 jobs:
-  testing:
-    name: Unit Testing
-    # needs: [integrationTest]
+  build-msix:
+    name: Build MSIX
     runs-on: windows-latest
     steps:
-      - uses: actions/checkout@v1
-      - uses: actions/setup-java@v1
-        with:
-          java-version: "8.x"
-      - uses: subosito/flutter-action@master
-        with:
-          # flutter-version: '1.22.3'
-          channel: "stable"
-      # pause test on server for now
-      - run: git submodule update --init
-      - run: flutter pub get
-      # - run: ./install.sh
-      - run: flutter test
-  windows:
-    name: windowsInstaller
-    needs: [testing]
-    runs-on: windows-latest
-    steps:
-      - uses: actions/checkout@v1
+      - uses: actions/checkout@v2
       - uses: actions/setup-java@v1
         with:
           java-version: "8.x"
@@ -36,10 +19,68 @@ jobs:
           flutter-version: "2.8.1"
           channel: "stable"
       - run: git submodule update --init
-      - run: flutter pub get
+      - name: Configure Missing files
+        run: |
+          echo "$INDEX" >> web/index.html
+          echo "$CONFIGDART" >> packages/flipper_login/lib/config.dart
+          echo "$FIREBASEOPTIONS" >> lib/firebase_options.dart
+        env:
+          INDEX: ${{ secrets.INDEX }}
+          CONFIGDART: ${{ secrets.CONFIGDART }}
+          FIREBASEOPTIONS: ${{ secrets.FIREBASEOPTIONS }}
+      - run: dart pub global activate melos 2.9.0
+      - name: "Run Melos bootstrap"
+        run: melos bootstrap
       - run: flutter config --enable-windows-desktop
-      - run: flutter build windows
       - run: flutter pub run msix:create
+      - name: Upload MSIX to Artifacts
+        uses: actions/upload-artifact@v2
+        with:
+          name: msix
+          path: build/windows/runner/Release/flipper.msix
+
+  deploy-msix:
+    name: Deploy MSIX
+    needs: [build-msix]
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v2
+      - name: Check Build Status
+        run: |
+          flutter build windows
+
+          if [[ $? -eq 0 ]]; then
+            echo "Build succeeded."
+            echo "Uploading MSIX file to release."
+            # Upload MSIX file to release here.
+          else
+            echo "Build failed."
+            echo "Aborting action."
+            exit 1
+          fi
+      - name: Check Environment Variables
+        run: |
+          echo "Checking environment variables."
+
+          if [[ -z $INDEX ]]; then
+            echo "Environment variable INDEX is not set."
+            echo "Aborting action."
+            exit 1
+          fi
+
+          if [[ -z $CONFIGDART ]]; then
+            echo "Environment variable CONFIGDART is not set."
+            echo "Aborting action."
+            exit 1
+          fi
+
+          if [[ -z $FIREBASEOPTIONS ]]; then
+            echo "Environment variable FIREBASEOPTIONS is not set."
+            echo "Aborting action."
+            exit 1
+          fi
+
+          echo "Environment variables are set."
       - name: Create a Release in GitHub
         uses: ncipollo/release-action@v1
         with:
@@ -47,24 +88,14 @@ jobs:
           tag: v1.58.0.0
           token: ${{ secrets.GH_TOKEN }}
           # commit: ${{ github.sha }}
-      - name: Upload  windows installer
-        uses: actions/upload-artifact@v2
+      - name: Upload winInstaller File
+        uses: actions/upload-release-asset@v2
         with:
-          name: winInstaller
-          path: build/windows/runner/Release/flipper.msix
-          # TODO: https://github.com/marketplace/actions/windows-store-publish use this to also publish to windows store.
-  slackNotification:
-    name: Slack Notification
-    needs: [windows]
-    runs-on: ubuntu-latest
-    steps:
-      - uses: actions/checkout@v2
+          asset_path: build/windows/runner/Release/winInstaller.exe
+          asset_name: winInstaller.exe
+          release: ${{ github.event.release.name }}
+          token: ${{ secrets.GH_TOKEN }}
       - name: Slack Notification
         uses: rtCamp/action-slack-notify@v2
         env:
           SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
-# https://techcommunity.microsoft.com/t5/windows-dev-appconsult/enable-ci-cd-for-windows-apps-with-github-actions-and-azure/ba-p/1453991
-# C:\Users\Sone\AppData\Local\Pub\Cache\hosted\pub.dartlang.org\msix-2.1.3\lib\assets
-# done.
-
-# https://deveenrath.medium.com/flutter-pos-receipt-printing-ada7c1c7c33f
